'use client';

import { useEffect } from 'react';

export default function ExposureCalculator() {
  useEffect(() => {
    let disposed = false;
    let cleanup: (() => void) | undefined;

    import('@/exposure/exposure_calculator').then(({ initExposureCalculator }) => {
      if (!disposed) cleanup = initExposureCalculator();
    });

    return () => {
      disposed = true;
      cleanup?.();
    };
  }, []);

  return (
    <main
      className={`
        mx-auto
        w-[min(1180px,calc(100%-140px))]
        pt-32
        pb-24
        max-[767px]:w-[min(calc(100%-38px),620px)]
        max-[767px]:pt-24
      `}
    >
      <header
        className={`
          grid
          grid-cols-[1fr_auto]
          items-end
          gap-8
          border-b
          border-[var(--color-line)]
          pb-8
          max-[560px]:grid-cols-1
        `}
      >
        <div>
          <p
            className={`
              mb-5
              text-[0.62rem]
              tracking-[0.14em]
              text-[var(--color-muted)]
              uppercase
            `}
          >
            Tools / 01
          </p>
          <h1
            className={`
              text-[clamp(3rem,7vw,5.6rem)]
              leading-[0.88]
              font-medium
              tracking-[-0.055em]
            `}
          >
            曝光計算器
          </h1>
          <p
            className={`
              mt-6
              max-w-[34rem]
              text-[0.92rem]
              leading-[1.8]
              text-[var(--color-muted)]
            `}
          >
            先將目前參數設為基準，再選擇想要的曝光偏移。鎖定不想改變的參數，計算器會自動調整其餘項目。
          </p>
        </div>
        <button
          id="resetBaseline"
          className={`
            min-h-11
            border
            border-[var(--color-text)]
            px-4
            text-[0.62rem]
            tracking-[0.1em]
            uppercase
            transition-colors
            hover:bg-[var(--color-text)]
            hover:text-[var(--color-bg)]
          `}
          type="button"
        >
          設目前為基準
        </button>
      </header>

      <div
        className={`
          grid
          grid-cols-[minmax(0,7fr)_minmax(320px,5fr)]
          gap-12
          max-[900px]:grid-cols-1
          max-[900px]:gap-0
        `}
      >
        <div
          className={`
            min-w-0
          `}
        >
      <section
        className={`
          relative
          mt-10
          border-b
          border-[var(--color-line)]
          bg-[var(--color-blue)]
          px-6
          py-6
          text-white
          max-[560px]:px-4
        `}
        aria-live="polite"
      >
        <span
          className={`
            absolute
            top-0
            left-0
            bg-[var(--color-red)]
            px-3
            py-1
            text-[0.55rem]
            tracking-[0.14em]
            uppercase
          `}
        >
          Step 01 / 目標
        </span>
        <div
          className={`
            mt-7
            mb-4
            flex
            items-baseline
            justify-between
            gap-[13px]
          `}
        >
          <span
            className={`
              text-[0.6rem]
              tracking-[0.16em]
              text-white/60
            `}
          >
            目前曝光偏移
          </span>
          <strong
            id="errorReading"
            className={`
              text-[clamp(2rem,5vw,3.6rem)]
              leading-none
              font-normal
            `}
          >
            0.0 EV
          </strong>
        </div>
        <div
          className={`
            grid
            min-h-[47px]
            grid-cols-[72px_1fr_82px_68px]
            items-center
            gap-[13px]
            max-[560px]:grid-cols-[58px_1fr_65px]
            max-[560px]:gap-[9px]
          `}
        >
          <label
            className={`
              text-[0.68rem]
              tracking-[0.09em]
            `}
            htmlFor="targetEv"
          >
            EV
          </label>
          <input
            id="targetEv"
            className={`
              w-full
              accent-white
            `}
            type="range"
            min="-8"
            max="8"
            step="0.1"
            defaultValue="0"
          />
          <output
            id="targetEvLabel"
            className={`
              text-right
              text-[1.2rem]
              whitespace-nowrap
              max-[560px]:col-start-3
            `}
          >
            0.0 EV
          </output>
          <label
            className={`
              justify-self-end
              text-[0.56rem]
              tracking-[0.06em]
              text-white/70
            `}
          >
            <input
              id="lockEv"
              className={`
                accent-white
              `}
              type="checkbox"
            />{' '}
            保持目標
          </label>
        </div>
        <p
          className={`
            mt-3
            border-t
            border-white/20
            pt-3
            text-[0.68rem]
            leading-[1.7]
            text-white/60
          `}
        >
          向右增加曝光，向左減少曝光。開啟「保持目標」後，改變任一參數時會自動補償。
        </p>
      </section>

      <section
        className={`
          relative
          mt-10
          border-b
          border-[var(--color-line)]
          pt-12
          pb-6
        `}
      >
        <div
          className={`
            absolute
            top-0
            left-0
            flex
            w-full
            items-center
            justify-between
            border-b
            border-[var(--color-line)]
            pb-3
          `}
        >
          <span
            className={`
              text-[0.6rem]
              tracking-[0.14em]
              uppercase
            `}
          >
            Step 02 / 相機參數
          </span>
          <span
            className={`
              text-[0.58rem]
              text-[var(--color-muted)]
            `}
          >
            勾選鎖定 = 不參與自動調整
          </span>
        </div>
        <div
          id="cameraControls"
          className={`
            [&_.parameter-row]:grid
            [&_.parameter-row]:min-h-[47px]
            [&_.parameter-row]:grid-cols-[72px_1fr_82px_68px]
            [&_.parameter-row]:items-center
            [&_.parameter-row]:gap-[13px]
            [&_.parameter-row]:py-3
            [&_.parameter-row+_.parameter-row]:border-t
            [&_.parameter-row+_.parameter-row]:border-[rgba(10,10,10,0.12)]
            [&_.parameter-row>label:first-child]:text-[0.68rem]
            [&_.parameter-row>label:first-child]:tracking-[0.09em]
            [&_input[type=range]]:w-full
            [&_input[type=range]]:accent-[var(--color-text)]
            [&_output]:text-right
            [&_output]:text-[1.08rem]
            [&_output]:font-semibold
            [&_output]:whitespace-nowrap
            [&_.lock]:justify-self-end
            [&_.lock]:text-[0.56rem]
            [&_.lock]:tracking-[0.06em]
            [&_.lock]:text-[var(--color-muted)]
            [&_.lock_input]:accent-[var(--color-text)]
            [&_[data-direct]]:cursor-text
            [&_[data-direct]:focus]:border-b
            [&_[data-direct]:focus]:border-[var(--color-line)]
            [&_[data-direct]:focus]:outline-none
            [&_.long-exposure]:col-span-2
            [&_.long-exposure]:col-start-2
            [&_.long-exposure]:-mt-1
            [&_.long-exposure]:border-0
            [&_.long-exposure]:border-b
            [&_.long-exposure]:border-[var(--color-line)]
            [&_.long-exposure]:bg-transparent
            [&_.long-exposure]:py-1
            [&_.long-exposure]:text-[0.72rem]
            [&_.long-exposure]:outline-none
            max-[560px]:[&_.parameter-row]:grid-cols-[58px_1fr_65px]
            max-[560px]:[&_.parameter-row]:gap-[9px]
            max-[560px]:[&_output]:col-start-3
            max-[560px]:[&_.lock]:col-start-1
            max-[560px]:[&_.lock]:row-start-2
          `}
        />
      </section>
        </div>

        <aside
          className={`
            min-w-0
            border-l
            border-[var(--color-line)]
            pl-12
            max-[900px]:mt-12
            max-[900px]:border-l-0
            max-[900px]:border-t
            max-[900px]:pl-0
          `}
          aria-label="選用曝光附件"
        >
      <section
        className={`
          mt-10
          border-b
          border-[var(--color-line)]
          py-[18px]
        `}
      >
        <div
          className={`
            mb-[10px]
            flex
            items-center
            justify-between
          `}
        >
          <span
            className={`
              text-[1.5rem]
              font-semibold
            `}
          >
            ND 濾鏡
            <small
              className={`
                ml-3
                text-[0.56rem]
                font-normal
                tracking-[0.12em]
                text-[var(--color-muted)]
                uppercase
              `}
            >
              Optional
            </small>
          </span>
          <div>
            <label
              className={`
                mr-[14px]
                text-[0.56rem]
                tracking-[0.06em]
                text-[var(--color-muted)]
              `}
            >
              <input
                id="lockNd"
                className={`
                  accent-[var(--color-text)]
                `}
                type="checkbox"
              />{' '}
              鎖定
            </label>
            <button
              id="addNd"
              className={`
                border-b
                border-[var(--color-line)]
                pb-[3px]
                text-[0.58rem]
                tracking-[0.08em]
              `}
              type="button"
            >
              + 新增
            </button>
          </div>
        </div>
        <div
          id="ndStack"
          className={`
            text-[1.35rem]
            text-[rgba(10,10,10,0.72)]
          `}
        >
          無濾鏡
        </div>
        <p
          className={`
            mt-2
            text-[0.68rem]
            leading-[1.7]
            text-[var(--color-muted)]
          `}
        >
          裝上 ND 濾鏡時才需要新增。多個濾鏡會自動累加減光檔數。
        </p>
        <div
          id="ndList"
          className={`
            mt-[10px]
            grid
            gap-[7px]
            [&_.nd-card]:grid
            [&_.nd-card]:grid-cols-[1fr_74px_auto]
            [&_.nd-card]:items-center
            [&_.nd-card]:gap-3
            [&_.nd-card]:border
            [&_.nd-card]:border-[var(--color-line)]
            [&_.nd-card]:p-[13px]
            [&_input[type=range]]:w-full
            [&_input[type=range]]:accent-[var(--color-text)]
            [&_output]:text-right
            [&_output]:text-[1.35rem]
            [&_.remove]:text-[0.55rem]
            [&_.remove]:tracking-[0.08em]
            [&_.remove]:text-[var(--color-muted)]
          `}
        />
      </section>

      <section
        className={`
          border-b
          border-[var(--color-line)]
          py-[18px]
        `}
      >
        <div
          className={`
            mb-[10px]
            flex
            items-center
            justify-between
          `}
        >
          <span
            className={`
              text-[1.5rem]
              font-semibold
            `}
          >
            閃燈
            <small
              className={`
                ml-3
                text-[0.56rem]
                font-normal
                tracking-[0.12em]
                text-[var(--color-muted)]
                uppercase
              `}
            >
              Optional
            </small>
          </span>
          <button
            id="addFlash"
            className={`
              border-b
              border-[var(--color-line)]
              pb-[3px]
              text-[0.58rem]
              tracking-[0.08em]
            `}
            type="button"
          >
            + 新增
          </button>
        </div>
        <p
          className={`
            text-[0.68rem]
            leading-[1.7]
            text-[var(--color-muted)]
          `}
        >
          需要混合環境光與閃燈時使用。可記錄現有功率，或用 GN 與距離估算輸出。
        </p>
        <div
          id="flashList"
          className={`
            mt-[10px]
            grid
            gap-[7px]
            [&_.flash-card]:border
            [&_.flash-card]:border-[var(--color-line)]
            [&_.flash-card]:p-[13px]
            [&_.flash-top]:flex
            [&_.flash-top]:items-center
            [&_.flash-top]:gap-[10px]
            max-[560px]:[&_.flash-top]:flex-wrap
            [&_.flash-top>input]:min-w-0
            [&_.flash-top>input]:flex-1
            [&_.flash-top>input]:text-[1.15rem]
            [&_.flash-mode]:flex
            [&_.flash-mode]:gap-[10px]
            max-[560px]:[&_.flash-mode]:order-3
            max-[560px]:[&_.flash-mode]:w-full
            [&_.flash-mode_button]:py-[5px]
            [&_.flash-mode_button]:text-[0.56rem]
            [&_.flash-mode_button]:tracking-[0.06em]
            [&_.flash-mode_button]:opacity-45
            [&_.flash-mode_button.active]:border-b
            [&_.flash-mode_button.active]:border-[var(--color-text)]
            [&_.flash-mode_button.active]:opacity-100
            [&_.flash-fields]:mt-[13px]
            [&_.flash-fields]:grid
            [&_.flash-fields]:grid-cols-3
            [&_.flash-fields]:items-end
            [&_.flash-fields]:gap-3
            max-[560px]:[&_.flash-fields]:grid-cols-2
            [&_.flash-fields_label]:grid
            [&_.flash-fields_label]:gap-[5px]
            [&_.flash-fields_label]:text-[0.75rem]
            [&_.flash-fields_label]:tracking-[0.07em]
            [&_.flash-fields_label]:text-[var(--color-muted)]
            [&_.flash-fields_label_strong]:text-[1.25rem]
            [&_.flash-fields_label_strong]:tracking-normal
            [&_.flash-fields_label_strong]:text-[var(--color-text)]
            [&_.flash-fields_input]:w-full
            [&_.flash-fields_button]:min-h-[27px]
            [&_.flash-fields_button]:border-b
            [&_.flash-fields_button]:border-[var(--color-line)]
            [&_.flash-fields_button]:text-[0.57rem]
            [&_.flash-fields_button]:tracking-[0.08em]
            [&_.flash-status]:mt-3
            [&_.flash-status]:text-[0.82rem]
            [&_.flash-status]:tracking-[0.06em]
            [&_.flash-status]:text-[var(--color-muted)]
            [&_.flash-status_strong]:ml-[6px]
            [&_.flash-status_strong]:text-[1.3rem]
            [&_.flash-status_strong]:text-[var(--color-text)]
            [&_.remove]:text-[0.55rem]
            [&_.remove]:tracking-[0.08em]
            [&_.remove]:text-[var(--color-muted)]
            [&_.flash-card_input]:border-0
            [&_.flash-card_input]:border-b
            [&_.flash-card_input]:border-[var(--color-line)]
            [&_.flash-card_input]:bg-transparent
            [&_.flash-card_input]:py-[5px]
            [&_.flash-card_input]:text-[0.7rem]
            [&_.flash-card_input]:outline-none
          `}
        />
      </section>
        </aside>
      </div>
    </main>
  );
}
